# Generated by Django 4.2.7 on 2023-11-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0002_alter_booking_table_alter_floor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credentials',
            table='Credentials',
        ),
    ]
