# Generated by Django 4.2.7 on 2023-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0004_parkingslot_physical_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
