# Generated by Django 4.2.7 on 2023-11-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0008_remove_floor_height_limit_remove_floor_weigh_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslotrules',
            name='parking_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingApp.parkingslot'),
        ),
    ]
