# Generated by Django 4.2.7 on 2023-11-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0009_alter_parkingslotrules_parking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslotrules',
            name='available',
        ),
    ]
